version: 2
jobs:
  build:
    working_directory: ~/code
    docker:
      - image: circleci/android:api-26-alpha
    environment:
      JVM_OPTS: -Xmx3200m
      ANDROID_HOME: /opt/android
    dependencies:
      pre:
        - mkdir $ANDROID_HOME/licenses
        - echo [ANDROID_SDK_LICENSE] >> $ANDROID_HOME/licenses/android-sdk-license
        - echo y | android update sdk --no-ui --all --filter "build-tools-25.0.2"
        - echo y | android update sdk --no-ui --all --filter "extra-android-m2repository,extra-google-m2repository"
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Chmod permissions
          command: sudo chmod +x ./gradlew
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - store_artifacts:
          path: app/build/reports
          destination: reports
      - store_test_results:
          path: app/build/test-results
      # See https://circleci.com/docs/2.0/deployment-integrations/ for deploy examples